### ISSUE TITLE
missing examples

### ISSUE THREAD

**Issue by sanaeefar-saeed** [zyairelai/futures-omax#2]
hi, please add few examples for each method
open order ,close order, trailing stop, .....

**Comment by zyairelai** [comment]
Hi Sanaeefar,

Kindly refer to `binance_futures.py` line 45 onwards, the open order and close order that you meant are already implemented as `Open_Position()` and `Close_Position`. Besides, Trailing Stop, Take Profit and Stoploss aren't really suitable on this strategy. However, you can simply add those features onto `strategy.py` because I had already written the wrappers for those. However, strongly NOT RECOMMENDED
