### ISSUE TITLE
Support testnet market

### ISSUE THREAD

**Issue by duythien0912** [zyairelai/futures-omax#4]
It awsome if we have demo for the bot on testnet binance market

https://testnet.binancefuture.com/en/futures/BTCUSDT

**Comment by zyairelai** [comment]
I wish to, but I can't. 
Binance itself does not have API-intergration on Binance Testnet. 
And the reason is pretty simple, they want to earn our money. 

Let's check the questions below:

Q1: Do we need a lot of time and money to do testing to have a high win rate Trading Bot?
Answer: Definitely yes. We will lose a lot money while doing testing (Which I already did when I started this project)

Q2: If we have a 100% win rate trading bot, who will lose the money while we are winning? 
Answer: Binance is the one who loses money.

Q3: Do you think Binance will me develop a high win rate trading bot without me having to risk my money? 
Answer: I guess you already know the answer.

Therefore, if you want to do testing, your have to spend your real money, with minimum trade amount, which is the recommended amount on `config.py`. 

Good Luck and Happy Trading!

**Comment by duythien0912** [comment]
I think we can store in a variable like total_wallet and only send the request when production

Other with other cases just calculate and show on console log

Controlled some option on config.py live `sandbox: true`

**Comment by duythien0912** [comment]
But I totally agree with you on the above points 🔥

**Comment by duythien0912** [comment]
Need to test on real money

**Comment by zyairelai** [comment]
> I think we can store in a variable like `wallet_money` and only send the request when production
> 
> Other with other cases just calculate and show on console log

I've done this in the beginning, however, i couldn't find a way to check the current status if I do so, which will lead to trouble on double ordering.

If you like to see the entry or exit, you can set `live_trade = False` in `config.py`. This will not trigger order with new money. However, back test with historical data and see the PnL result on this `futures-omax` is nearly impossible due to the strategy itself requires real time candlestick formation in the unit of seconds.

**Comment by duythien0912** [comment]
Yeah will try your too

I also found this lib support testnet

https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api
https://binance-docs.github.io/apidocs/futures/en/#testnet

Maybe I can work on it and let try together : D

**Comment by zyairelai** [comment]
> Yeah will try your too
> 
> I also found this lib support testnet
> 
> https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api
> https://binance-docs.github.io/apidocs/futures/en/#testnet
> 
> Maybe I can work on it and let try together : D

You can retrieve the candlestick and almost everything but you can't place an order using Testnet API. 
You can join this Telegram group and chat around, many are complaining about Testnet not working blablabla since last year till now, it is not working for some reason. 

https://t.me/binance_api_english
